### ISSUE TITLE
Upload bugs

### ISSUE THREAD

**Issue by N214** [codenoid/temporar#1]
Hi, thank you for this very cool project. 

However, I could not make it work correctly. Multiple issue encountered:

- GUI interface does not accept upload, got a undefined and GUI stuck at "Processing file" 
<img width="1380" alt="image" src="https://github.com/codenoid/temporar/assets/34739662/f06cafd7-1a8f-42d7-a94f-d3c02e0023ed">

The upload was a PDF file but seems like the behavior changes between the file type. And in the S3 buket, we endup with a bunch of this: 
<img width="1234" alt="image" src="https://github.com/codenoid/temporar/assets/34739662/7668b400-724f-4766-b6ac-f00bdb0ba3f4">

- Using an API testing client, it behaves correctly:
<img width="1278" alt="image" src="https://github.com/codenoid/temporar/assets/34739662/c897c7c9-2a16-4e99-9e83-699e0bcf496b">
 
<img width="1192" alt="image" src="https://github.com/codenoid/temporar/assets/34739662/4b40e889-a452-46a4-ab7d-42bd6d2337d2">

- There is also a credential conflict, I could not make it work with
```go
		config.WithEndpointResolverWithOptions(r2Resolver),
		config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(
			os.Getenv("S3_ACCESS_KEY"),
			os.Getenv("S3_SECRET_KEY"),
			"")),
```
Changed to the default config and since we are taking the credentials from the environment variables, the SDK will automatically use `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and added `AWS_REGION`
```go
cfg, err := config.LoadDefaultConfig(context.TODO())
```
Here is my env file:
```
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=
S3_BUCKET_NAME=buk-test-stg
BIND_ADDR="127.0.0.1:4040"
```

**Comment by codenoid** [comment]
I'm sorry, the frontend folder was missing the .env files, [I just push a quick-fix](https://github.com/codenoid/temporar/blob/main/frontend/.env)

the reason is because the `import.meta.env.VITE_BASE_URL` part are detected as undefined, It should be just an empty string, but I may change the code later

https://github.com/codenoid/temporar/blob/29845aa49a4bf3ea04c5e856a0297cbccb884ec8/frontend/src/routes/%2Bpage.svelte#L53

**Comment by N214** [comment]
No problem, I figured out it was more a frontend issue but being not familiar with Svelt, I did not want to dive in.

As for the credential conflict, I do think, it would be easier to use the AWS default env variables, what do you think?
